---
- name: install pre-requisites
  pip:
    name:
      - pyyaml
      - boto3 
      - botocore

- name: Create AWS ECR repositories
  community.aws.ecs_ecr:
    name: "{{ item.name }}"
    state: present
    profile: "{{ AWS_PROFILE  }}"
    region: "{{ AWS_REGION }}"
  loop: "{{ ecr_repositories }}"
  register: ecr_results

- name: Set repository policies if defined
  community.aws.ecs_ecr:
    name: "{{ item.name }}"
    policy: "{{ item.policy | to_json }}"
    state: present
    profile: "{{ AWS_PROFILE  }}"
    region: "{{ AWS_REGION }}"
  loop: "{{ ecr_repositories }}"
  when: "item.policy is defined"
