- name: Create Namespace
  kubernetes.core.k8s:
    state: present
    api_version: v1
    kind: Namespace
    name: bitbucket-runner
    kubeconfig: "{{ kubeconfig_path }}"

- name: Create Service Account
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'service-account.yml.j2') }}"
    kubeconfig: "{{ kubeconfig_path }}"

- name: Deploy Bitbucket Runner
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'bitbucket-runner-deployment.yml.j2') }}"
    kubeconfig: "{{ kubeconfig_path }}"
