replicaCount: 1

image:
  repository: redis
  tag: "7-alpine"
  pullPolicy: IfNotPresent

auth:
  enabled: true
  password: "somethingsecure"

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: false
  accessModes:
    - ReadWriteOnce
  size: 1Gi

redisConfig:
  enabled: true
  config: |
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    appendonly yes
    save 60 1
